spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yiblog?useSSL=false&serverTimezone=UTC
    username: root
    password: zxc47POI!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.zhouyi: debug
  file: log/blog-dev.log
